services:
  postgres:
    image: postgres:17
    container_name: prestige-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: black-winter
      POSTGRES_PASSWORD: shahdeo69
      POSTGRES_DB: prestige
    ports:
      - "5432:5432"
    volumes:
      - prestige_postgres_data:/var/lib/postgresql/data

volumes:
  prestige_postgres_data: